paper:
  rcParams:
    text.usetex: True
    text.latex.preamble: '\usepackage{lmodern}'
    axes.titlesize: 7
    axes.labelsize: 7
    xtick.labelsize: 7
    ytick.labelsize: 7
    legend.fontsize: 7
  legend_info:
    mode_order: ["full","FE"]
    legend_labels: {"full":"Full","FE":"Forward Equivalent"}
    sns_palette: ["#1f77b4", "#ff7f0e"]
  fig_dpi: 300
